# Linear Regression Model

## Clean and Manage Dataset

In [94]:
import pandas as pd
import numpy as np
from pathlib import Path

DATA = Path(r'C:\Users\minju\Desktop\CSProjects\whaleTracker\predictionModel\dwca-futurismo-data')

occ  = pd.read_csv(DATA / 'occurrence.txt',                sep='\t', low_memory=False)
evt  = pd.read_csv(DATA / 'event.txt',                     sep='\t', low_memory=False)
emof = pd.read_csv(DATA / 'extendedmeasurementorfact.txt', sep='\t', low_memory=False)

In [23]:
print(df.columns.tolist())

['id_occ', 'type', 'license', 'institutionCode_occ', 'collectionCode', 'datasetName_occ', 'basisOfRecord', 'occurrenceID', 'recordedBy', 'organismQuantity', 'organismQuantityType', 'sex', 'lifeStage', 'occurrenceStatus', 'associatedTaxa', 'eventID', 'verbatimIdentification', 'scientificNameID', 'scientificName', 'kingdom', 'phylum', 'class', 'order', 'family', 'genus', 'scientificNameAuthorship', 'id_evt', 'institutionCode_evt', 'datasetName_evt', 'parentEventID', 'eventDate', 'samplingProtocol', 'waterBody', 'islandGroup', 'country', 'countryCode', 'stateProvince', 'minimumDepthInMeters', 'maximumDepthInMeters', 'locationRemarks', 'decimalLatitude', 'decimalLongitude', 'geodeticDatum', 'coordinateUncertaintyInMeters', 'footprintWKT', 'id', 'measurementID', 'occurrenceID_emof', 'measurementType', 'measurementTypeID', 'measurementValue', 'measurementValueID', 'measurementUnit', 'measurementUnitID', 'measurementRemarks']

In [100]:
keep_list = ['id', 'occurrenceID', 'organismQuantity', 'organismQuantityType', 'sex',
             'lifeStage', 'associatedTaxa', 'eventID',
             'verbatimIdentification', 'scientificNameID', 'scientificName',
             'kingdom', 'phylum', 'class', 'order', 'family', 'genus']
occ = occ.drop(columns=[col for col in occ.columns if col not in keep_list])

keep_listevt = ['id', 'institutionCode', 'eventID', 'parentEventID', 'eventDate'
                , 'decimalLatitude', 'decimalLongitude',
                'coordinateUncertaintyInMeters', 'footprintWKT']
evt = evt.drop(columns=[col for col in evt.columns if col not in keep_listevt]) 

keep_list_emof = ['id', 'measurementID', 'occurrenceID', 'measurementType', 'measurementTypeID',
                  'measurementValue', 'measurementValueID', 'measurementUnit'
]
                  
emof = emof.drop(columns=[col for col in emof.columns if col not in keep_list_emof]) 

print(occ['verbatimIdentification'].value_counts())


df = (occ.merge(evt,  on='eventID', how='outer', suffixes=('_occ', '_evt'))
         .merge(emof, left_on='id_occ', right_on='id', how='outer', suffixes=('', '_emof')))

print(df.shape)
df.head()

Pm                         6213
Dd                         4839
Tt                         2694
Bp                         1765
Sf                         1493
Gg                          618
Bb                          596
Bm                          449
Cc                          312
Gm                          274
Sc                          246
Mn                          202
Be                          122
Oo                           73
Pc                           72
baleias-de-bico              64
golfinhos                    58
baleia de barbas             49
Mb                           49
Ba                           37
Md                           20
tartaruga de couro           19
Ha                           18
tubarão martelo              17
jamanta                      15
Mm                            9
peixe lua                     8
Zc                            6
espadim                       6
tubarão baleia                5
tartaruga                     4
Balaenoptera sp.              4
espadarte                     4
tuna                          3
espadim branco                3
Gmac                          3
espadim azul                  3
Mobula sp.                    3
foca cinzenta                 2
Stenella                      2
alma negra                    1
corvo marinho                 1
frulho                        1
Mola sp.                      1
tintureira                    1
peixe voador                  1
bluntnose sixgill shark       1
tartaruga verde               1
estapagado                    1
bonito                        1
Name: verbatimIdentification, dtype: int64
(221903, 33)

,id_occ,occurrenceID,organismQuantity,organismQuantityType,sex,lifeStage,associatedTaxa,eventID,verbatimIdentification,scientificNameID,...,coordinateUncertaintyInMeters,footprintWKT,id,measurementID,occurrenceID_emof,measurementType,measurementTypeID,measurementValue,measurementValueID,measurementUnit
0,FUT_SM0818_cruise0001:encounter00001,9c23825c-8ef8-4c18-9251-b928e9cc9280,1-30,minimum to maximum number of individuals,NaN,NaN,NaN,FUT_SM0818_cruise0001:encounter00001,Tt,urn:lsid:marinespecies.org:taxname:137111,...,50.134409,POINT(-25.4865666666667 37.6901833333333),FUT_SM0818_cruise0001:encounter00001,5f0c103d-2b0e-4149-938e-8332b516c0fe,NaN,Beaufort wind force,http://vocab.nerc.ac.uk/collection/P01/current...,5,NaN,Beaufort scale
1,FUT_SM0818_cruise0001:encounter00001,9c23825c-8ef8-4c18-9251-b928e9cc9280,1-30,minimum to maximum number of individuals,NaN,NaN,NaN,FUT_SM0818_cruise0001:encounter00001,Tt,urn:lsid:marinespecies.org:taxname:137111,...,50.134409,POINT(-25.4865666666667 37.6901833333333),FUT_SM0818_cruise0001:encounter00001,d9ac0d5e-78f4-4641-a307-ee2549e8ed94,NaN,visibility,http://vocab.nerc.ac.uk/collection/P01/current...,3,NaN,%
2,FUT_SM0818_cruise0001:encounter00001,9c23825c-8ef8-4c18-9251-b928e9cc9280,1-30,minimum to maximum number of individuals,NaN,NaN,NaN,FUT_SM0818_cruise0001:encounter00001,Tt,urn:lsid:marinespecies.org:taxname:137111,...,50.134409,POINT(-25.4865666666667 37.6901833333333),FUT_SM0818_cruise0001:encounter00001,37fd179c-d130-49fb-9042-01070f385af1,NaN,sampling instrument name,http://vocab.nerc.ac.uk/collection/P01/current...,observers,http://vocab.nerc.ac.uk/collection/L05/current...,NaN
3,FUT_SM0818_cruise0001:encounter00001,9c23825c-8ef8-4c18-9251-b928e9cc9280,1-30,minimum to maximum number of individuals,NaN,NaN,NaN,FUT_SM0818_cruise0001:encounter00001,Tt,urn:lsid:marinespecies.org:taxname:137111,...,50.134409,POINT(-25.4865666666667 37.6901833333333),FUT_SM0818_cruise0001:encounter00001,be586af8-d1ad-47f7-a790-f42ad9206f66,9c23825c-8ef8-4c18-9251-b928e9cc9280,individual count (minimum estimate),NaN,1,NaN,individuals
4,FUT_SM0818_cruise0001:encounter00001,9c23825c-8ef8-4c18-9251-b928e9cc9280,1-30,minimum to maximum number of individuals,NaN,NaN,NaN,FUT_SM0818_cruise0001:encounter00001,Tt,urn:lsid:marinespecies.org:taxname:137111,...,50.134409,POINT(-25.4865666666667 37.6901833333333),FUT_SM0818_cruise0001:encounter00001,d5f45616-116b-4521-b14e-9668faddbae4,9c23825c-8ef8-4c18-9251-b928e9cc9280,individual count (maximum estimate),NaN,30,NaN,individuals

In [101]:
df.dtypes

id_occ                            object
occurrenceID                      object
organismQuantity                  object
organismQuantityType              object
sex                               object
lifeStage                         object
associatedTaxa                    object
eventID                           object
verbatimIdentification            object
scientificNameID                  object
scientificName                    object
kingdom                           object
phylum                            object
class                             object
order                             object
family                            object
genus                             object
id_evt                            object
institutionCode                   object
parentEventID                     object
eventDate                         object
decimalLatitude                  float64
decimalLongitude                 float64
coordinateUncertaintyInMeters    float64
footprintWKT                      object
id                                object
measurementID                     object
occurrenceID_emof                 object
measurementType                   object
measurementTypeID                 object
measurementValue                  object
measurementValueID                object
measurementUnit                   object
dtype: object

In [24]:
df.corr()

,minimumDepthInMeters,maximumDepthInMeters,decimalLatitude,decimalLongitude,coordinateUncertaintyInMeters
minimumDepthInMeters,NaN,NaN,NaN,NaN,NaN
maximumDepthInMeters,NaN,NaN,NaN,NaN,NaN
decimalLatitude,NaN,NaN,1.000000,-0.386077,-0.110386
decimalLongitude,NaN,NaN,-0.386077,1.000000,-0.297705
coordinateUncertaintyInMeters,NaN,NaN,-0.110386,-0.297705,1.000000

# Correlation Plots